### ISSUE TITLE
Change node shape and  node label position in D3graph ?

### ISSUE THREAD

**Issue by timkartar** [d3blocks/d3blocks#41]
Hello @erdogant :) This is a great library 👏. I am working on a  project where I would like to use different node shapes (rectangle/triangle/or potentially something custom built). Is there a way to change the shape from circle to say rectangle for specific nodes in D3graph ? Similarly the node labels are currently plotted outside the node. I want to put them inside. Any way to make such a change ? In general we will be needing to make such small tweaks of different kinds. If you could also point to the parts of the d3blocks source code where you implement these kind of things (and how), we will be willing to implement some ourselves (maybe contribute here too). Looking forward to your response. Best wishes.

**Comment by erdogant** [comment]
Yes, great suggestions! Your help would really be appreciated! There was once a great implementation over [here](https://github.com/erdogant/d3graph/issues/10) but the threshold functionality got broken. I have been experimenting with different node shapes. The square shape seems to correctly work but making it variable between different shapes seems to be more tricky.

See my example over [here](https://erdogant.github.io\docs\d3graph\d3graph\d3graph_square.html)

I addition, I created some updates last couple of days
* Functionality to set the slider theshold
* change the edge style
* Removing edge labels for the links that are removed using the threshold slider
* Zoom functionalities are back
* bug fix

**Comment by timkartar** [comment]
Thanks ! we recently figured out how your code is structured and we are able to modify it in various ways suitable for our use case is in a specific domain. So, we might not be able to contribute directly to the repo. But your code does serve as a great starting point.

**Comment by erdogant** [comment]
Fixed [both ](https://github.com/erdogant/d3graph/releases/tag/2.8.0) questions! Update to the latest version of d3graph with:

`pip install -U d3graph
`

See here [docs](https://erdogant.github.io/d3graph/pages/html/Examples.html#change-nodes-types) with example

**Comment by timkartar** [comment]
Hey thanks, although I have moved on from that job, this is nice to see. I believe we did a lot of overriding and wrote our own code etc. while still having a d3graph object base. Thanks for your help. 

Example of an entry of what we cooked, if you find it interesting: https://rnaprodb.usc.edu/1ivs  Lmk what you think!

**Comment by erdogant** [comment]
Oh wow I am impressed. This is really nice!
